---
# Take these from the "Naming Conventions in Playwaze"
# team type title: "Event"
# team title plural: "Entries"
# team title singular: "Entrie"
# team support title: "Cox (if required)"
# team captain singular: "Coach/Captain (optional)"
# team captain plural: "Coaches/Captains (optional)"
# team category singular: "Club"
# team category plural: "Clubs"

# The column number (starting from 0) of each field
teams report columns: 
  crew id: 0
  boat type: 5
  club: 6
  crew name: 7
  crew letter: 8
  seats: 10
  verified: 11
  captain: 12
  cox: 13
  captain name: 14
  cox name: 20
  notes: 21
  
# The column number (starting from 0) of each field
team members report columns:
  boat type: 2
  club: 3
  crew id: 4
  crew letter: 5
  crew name: 6
  member id: 7
  name: 8
  gender: 10
  dob: 11
  sr member number: 13
  membership type: 14
  membership expiry: 15
  rowing points: 16
  rowing novice: 17
  sculling points: 18
  sculling novice: 19
  primary club: 20
  additional clubs: 21
  first licence start date: 22
  composite clubs: 23

community members report columns:
  member id: 0
  name: 1
  dob: 3
  gender: 4
  sr member number: 6
  membership type: 7
  membership expiry: 8
  rowing points: 9
  rowing novice: 10
  sculling points: 11
  sculling novice: 12
  primary club: 13
  additional clubs: 14
  first licence start date: 15
  composite clubs: 16