---
# Take these from the "Naming Conventions in Playwaze"
# team type title: "Event"
# team title plural: "Entries"
# team title singular: "Entrie"
# team support title: "Cox (if required)"
# team captain singular: "Coach/Captain (optional)"
# team captain plural: "Coaches/Captains (optional)"
# team category singular: "Club"
# team category plural: "Clubs"

# The column number (starting from 0) of each field
teams report columns: 
  cox name: 16
  crew id: 0
  boat type: 5
  club: 6
  crew name: 7
  crew letter: 8
  seats: 10
  verified: 11
  captain: 11
  captain name: 13
  cox: 12
  
# The column number (starting from 0) of each field
team members report columns:
  boat type: 2
  club: 3
  crew id: 4
  crew letter: 5
  crew name: 6
  member id: 7
  name: 8
  gender: 9
  dob: 10
  sr member number: 12
  membership type: 13
  membership expiry: 14
  rowing points: 15
  rowing novice: 16
  sculling points: 17
  sculling novice: 18
  primary club: 19
  additional clubs: 20
  first licence start date: 21
  composite clubs: 22

community members report columns:
  member id: 0
  name: 1
  dob: 3
  gender: 4
  sr member number: 6
  membership type: 7
  membership expiry: 8
  rowing points: 9
  rowing novice: 10
  sculling points: 11
  sculling novice: 12
  primary club: 13
  additional clubs: 14
  first licence start date: 15
  composite clubs: 16